version: '3'

services:
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - nginx-log:/var/log/nginx
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    networks:
      - app-network
    command: certonly --webroot --webroot-path=/var/www/html --email webmaster@mgamlem3.com --agree-tos --no-eff-email -d mgamlem3.com  -d www.mgamlem3.com --dry-run

volumes:
  certbot-etc:
  certbot-var:
  nginx-log:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/michael/proxy-data
      o: bind

networks:
  app-network:
    driver: bridge  