version: '3'

services:
    proxy-server:
        restart: unless-stopped
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /home/michael/proxy-data:/etc/letsencrypt
            - /home/michael/proxy-data/mgamlem3.com:/certs/mgamlem3