version: '3'

services:
  webserver:
    image: node:latest
    container_name: webserver
    # restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./package.json:/app
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - app-network
    command: cd /app && yarn && node server.js

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email webmaster@mgamlem3.com --agree-tos --no-eff-email --staging -d mgamlem3.com  -d www.mgamlem3.com --dry-run

volumes:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  app-network:
    driver: bridge  