version: '3'

services:
    proxy-server:
        restart: unless-stopped
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /home/michael/proxy-data:/etc/letsencrypt
            - /etc/letsencrypt/live/mgamlem3.com:/etc/certs/mgamlem3